<a href="https://colab.research.google.com/github/kartik580/Ecommerce-order-Pandas/blob/main/Ecommerce_order_y_pj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Create a Pandas Series using these 1,000 order amounts.
##Perform the following:
Find the total order value.

Find the average order value.

Find the highest order amount.

Find the lowest order amount.

Find the top 10 highest order amounts.

Find the bottom 10 lowest order amounts.

Count how many orders are greater than ₹5,000.

Count how many orders are between ₹2,000 and ₹10,000.

Sort the order amounts in ascending order.

Sort the order amounts in descending order.

Find the index of the highest order.

Find the index of the lowest order.

Calculate the total revenue after applying a 15% discount on every order.

Find the number of orders above the average order value.

Find the difference between the highest and lowest order amount.

In [43]:
import numpy as np
import pandas as pd

In [48]:
order_amount=np.random.randint(200,25000,1000)

In [3]:
type(order_amount)

numpy.ndarray

In [4]:
orders=pd.Series(order_amount)
orders

0        869
1      20320
2      22959
3       6425
4      15033
       ...
995     4557
996     8946
997    15255
998    19776
999    15424
Length: 1000, dtype: int64

In [5]:
orders.shape

(1000,)

In [6]:
orders.ndim

1

In [7]:
orders.values

array([  869, 20320, 22959,  6425, 15033,  5970, 10016,  8625,  4381,
       16496,  3589, 15380,  1281, 19003,  2270,  6722,  2731,  5104,
       14805, 17394,  3971, 21485,  4462, 18096, 14772,  6561, 12920,
       18489,  1931, 10076,  4086, 20767,  6907, 16589, 22554, 24022,
        4311, 16466,  8003,  8596, 21958,  7148, 19600,  5871, 23199,
       19648, 10339, 16801, 20047,  7843, 19791,  9389,  1663, 14247,
        8663,   732,  4463, 20619,  4010,  9557,  4886, 11759, 12661,
        9455, 13256, 23744,  9782, 18145,  9133, 18910,  7991,  7130,
       24269,  8512, 17178,  5720,  3157, 17433, 16760, 24470, 15555,
        7149,  9228, 20940, 21207,  1056, 19699, 14709, 21773, 13524,
        4212, 14147,  9605, 21047,  6487, 18087, 15359, 14816, 10963,
        6088,  8526,  9173, 11450,  8395,   659, 14777,   446,  3063,
       15235, 19954,   857,  1827, 21895,  5928, 16127, 22525, 13468,
        3899, 14045, 21200, 19217, 22973, 15390,  8319, 16228,  6695,
        3770, 23823, 19857,  8791, 12522,  4191, 10023, 23273, 21555,
       13982,  8279, 23111,  2160,  6986, 17681, 17485,   503,  4784,
        8904, 24343, 14903, 17928, 16522,  4805,  4541, 21519,  3578,
        4094,  5572,  8043,  9950, 20893,  9259,  3680, 20558, 24945,
        2708, 22218,  3935, 19274, 15347, 18105, 21587,  3361,  2345,
       10273,  1603, 10741,  6734, 18384,  7542, 14058,  4975,  1344,
        6848, 24035,  9810,  9910, 19578,  8187,  8955,  7379, 12473,
       19164, 11870, 22216,  4678,  4573, 15142, 14845, 19483, 12938,
        6571,  1493, 11364,  1566,   368, 10441,  4405,  9373,  4128,
        7788, 14798, 15266, 24559,  3887, 18901,  4160,  4730,  5892,
         749, 12244, 23008,  7833, 15541,  8701,  5503, 13310, 22483,
       13908, 12731,  8590, 13833,  6060, 11572, 11173,  7203,  1744,
       13672, 17057,  4573, 22347,  3238,  7638,  3832, 10421,  4713,
       10010,  7136, 24716, 20190, 21910, 14703, 20662,  8313, 17408,
        2643, 11298, 14008, 18046, 22981, 12484, 23089,  3625, 23399,
       18525, 14999, 17120, 23538, 16008, 20586,  8479,  2129,  1832,
       24015,  4988,  4554, 22137, 14870, 12582,   448, 24073, 12932,
       21887, 19285,  3026, 19563,  1783,  7310, 12505, 13286, 21557,
       21651, 19522, 13659,  7460,  2517, 14445,  5194, 22558, 16354,
       13135, 11196,  2966,  2426,  2613, 21857,   990,  4034, 15429,
       13010, 14930, 24511, 14674, 17916,  1948,  7015,   542, 20186,
       10901,  4921, 12104,  7241, 11474, 17441, 12336, 11645, 12196,
       22640, 22601, 22427, 11819, 22092, 23563, 22066,  4451, 14775,
        7010,  6868, 22573,  7018, 18074,  9659, 16552, 14717, 16087,
       21850,   594, 14586,  1428, 19983,  5020, 14825, 13235, 20420,
       18617, 19345, 20756, 23974,  8018,  5856,   954, 20343, 23004,
         547, 16326, 20311,  9350, 11843, 15868,  4311,  7648,  8485,
       17645, 22756,  3437,  4148,  5116, 13244, 18065, 16256, 23137,
        1483,  4067,  8163,  4381,  4597, 21643, 14341, 18989, 21269,
        1012, 10882,  8186, 18728,  6326,  5896,  5150, 20212, 10490,
       19257, 13523, 22873,  2148, 10076, 20121,  5441, 14713, 20572,
       23293, 12194, 20208,  2598, 17771, 19295,  1456,  1179, 14570,
        8129, 20427,  9327,  3643, 13647, 24384, 11190,  8744,  2267,
       13774,  3252,  5085,  7272, 10122, 21501, 24152, 19960,  8202,
        9898, 12061,  6191, 19928, 22302, 15957, 17700, 10964,  1649,
       19567, 14661, 11017, 19150,  8958, 17454,  2519, 12995,   417,
       11656,  4953,   511, 17212, 14139, 16111, 12212, 20430, 18883,
         789, 16143,  2717,  3565,  1933,  8537, 10482, 24797, 19505,
        8759, 20699,  2307, 12310, 23263, 16548, 21445,  6063, 22062,
       15823,  5116,  6439, 19677,  9939,  9993,  6526,  2504, 11553,
       18053, 15391, 11089,  2468,  7754,  7559, 22977, 24969, 14921,
        1240,  3640,  7076,  1970,  3939,  9957, 17322, 17113,  4168,
        6214,  7693, 23703,  4727,  3110, 15420, 19575, 20846, 23973,
        7794, 13888, 14033, 11719,  5607,  4730,  7706, 22668,  8804,
       16889, 16084,  3148,  2008, 14657, 18926, 19553, 12210, 23790,
       13694, 18759, 20420,  5027, 15185, 14852,   593,  1017,  2666,
        9428, 18834,  5739, 22451, 11858, 10569,  2021,  7048, 14709,
       24359, 18935, 15790, 22500,  3783, 20041,  9231,   685,  3616,
       13663, 21602, 13175, 24998,  2311, 21616, 16614, 14539, 19395,
       17669, 14990, 10716,  8415, 10143,  1756, 17702, 10269,  8186,
       19655,  3637, 15369, 21838,  2848, 13196,  7601, 14788, 15610,
        2837, 20975, 24452,  2829,  1765, 14687, 19288, 23567,  8918,
       15253, 12395, 14441, 19854,  6329,  8862, 22759,  5841,  4469,
       16221, 19656, 11492, 16772, 22395, 16243, 18593,  2766,  4986,
        1664,  7322, 23409,  4236, 18359,  3811, 17226, 18913,  9538,
       14445, 15544,  4562, 16306,  7772, 12029,  1992, 16380, 12163,
        2918,  5514, 14014, 14457, 12850, 14607, 12146, 20049,   490,
        8298, 22543,  2672, 15821, 12543, 19221, 20417,  5915, 17185,
        9197, 19185, 16993,  8298, 16952, 19029,  7341, 21630,   308,
       12425, 20707,  1639, 10872,  6324, 16762,  3593,  1681,  7157,
       21169, 23487,  2932, 11238, 12047, 14515,  4894, 10470,  3245,
       16984,   949,  1237, 14084, 23032, 10143,  4749, 13006, 23605,
       20883, 13645,  8370, 15140,  8522, 16943, 12069, 24608, 17822,
       10747, 16685, 16621,  3039, 17332, 18503, 18566,  2881,  8465,
       16262,  7333, 22943,  4047,  6041,  6275, 24686, 21050,  6164,
       22930, 17736, 11902, 10288, 23269, 14229,  6373, 10150, 17201,
        9154, 10765, 15731,  9843, 14402,  5148, 10733, 10317,  4363,
       11829,  4842, 14483, 20299,  6951, 10221,  8654, 15253, 18961,
         581,  6853,  4971, 20136, 10949, 16476, 19095, 12387, 10728,
       22834,  3275,  4579,  1829,  1279, 14935, 12759, 10589, 18306,
       10219, 12387, 24535, 17096,  1991,  3460,  3285, 21371, 10976,
        8721,  5444,   218,  4495,  3643, 15592, 23505,  9199,  4141,
       11170, 16235, 18860, 10280,   478, 18530, 19535,  9317,  3658,
       15663, 24348, 16237, 15664, 11666, 19964, 13256, 15874,  3526,
       21670,  7067, 12941,  6342, 19931, 14717,  6689, 10637, 14411,
       19027, 23890,  5968, 21523, 15626, 15570,  2776, 24742,   531,
        2450, 12796, 21641,  4276,  8363, 18111,  5545, 22777, 11021,
       13803, 12531,  7945, 24436, 10475,  9631,  7879,  7018,  9368,
         670,  8646,  6768,  9990,  2938,  5672,  5736,  6353, 23819,
        5523, 12489, 20530, 17567, 20752,  5128,  9103,  6344,  8420,
       15768, 22621,  4231,  2347,  1583,  1012,  2784, 19577, 12715,
       22002,  7797, 17001,   373, 20078,  3826, 13181, 14261,  2466,
       10417, 22231,  9706,   828,  1572,  4918,  6697, 22230, 24723,
        9282,  9185, 23609, 21875, 18089,   348, 13264,  4897,  2759,
       20082,  2824,  9932,  4340, 12047,  7321,  5505, 24234,  5753,
       13182, 24306, 22542,  4525,  6510, 13268, 19465, 20334, 21210,
       18546, 12701, 17256,  7230,  2969,  2880,   857, 17406, 20535,
       14450, 10700, 14659,  1338,  4812, 24189, 10444, 12742, 24925,
       13746, 19513, 13573, 24884,  5996, 15439, 18295,  4728,  9717,
       19778,  7742,  3007,  7130, 13178,  3530, 21352, 19862, 14005,
        4050, 23337,  7632, 12904, 20488, 23836,  7132,   296, 17393,
       15922,  2848,  6913,  3871, 12633, 11356,  3575,  2393, 24450,
        9613,  3916, 21286,  1656, 17591, 18426, 24505, 13429, 19710,
       23557,  3532,  3320, 16984, 14660, 14079, 21106,  9956,  3288,
        4388, 20676, 20287,  5698, 24777,  9206, 13327,  5733, 11391,
       14766, 14994,  6481, 21446, 23873,  8777, 20513, 17584,  7799,
       10118, 11132,  9750, 11399,  3118,  4557,  8946, 15255, 19776,
       15424])

In [8]:
type(orders.values)

numpy.ndarray

In [9]:
orders.size

1000

In [10]:
orders.isnull()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [11]:
orders.index

RangeIndex(start=0, stop=1000, step=1)

In [12]:
orders.count()

np.int64(1000)

## orders uunique data

In [13]:
orders.unique().size

976

In [14]:
len(orders.unique())

976

#3 sum of the all orders

In [15]:
orders.sum()

np.int64(12169163)

In [16]:
#Find the average order value.
orders.mean()

np.float64(12169.163)

In [17]:
#Find the highest order amount.
orders.max()

24998

In [18]:
#Find the lowest order amount.
orders.min()

218

In [19]:
#Find the top 10 highest order amounts.
orders.nlargest(10)

561    24998
493    24969
161    24945
917    24925
921    24884
466    24797
976    24777
808    24742
872    24723
245    24716
dtype: int64

In [20]:
#Find the bottom 10 lowest order amounts.
orders.nsmallest(10)

767    218
943    296
656    308
878    348
202    368
858    373
449    417
106    446
276    448
778    478
dtype: int64

In [47]:
orders.nlargest().values[1]

np.int64(24969)

In [22]:
orders[orders>=5000]

1      20320
2      22959
3       6425
4      15033
5       5970
       ...
993    11399
996     8946
997    15255
998    19776
999    15424
Length: 781, dtype: int64

In [23]:
#Count how many orders are greater than ₹5,000.
orders[orders>=5000].size

781

In [24]:
#Count how many orders are between ₹2,000 and ₹10,000.
orders[(orders>=2000) & (orders<=10000)]

3      6425
5      5970
7      8625
8      4381
10     3589
       ...
989    7799
992    9750
994    3118
995    4557
996    8946
Length: 352, dtype: int64

In [25]:
orders[(orders>=2000) & (orders<=10000)].size

352

In [26]:
#Sort the order amounts in ascending order.
orders.sort_values()

767      218
943      296
656      308
878      348
202      368
       ...
921    24884
917    24925
161    24945
493    24969
561    24998
Length: 1000, dtype: int64

In [27]:
#Sort the order amounts in descending order
orders.sort_values(ascending=False)

561    24998
493    24969
161    24945
917    24925
921    24884
       ...
202      368
878      348
656      308
943      296
767      218
Length: 1000, dtype: int64

In [28]:
orders.sort_values().iloc[::-1]

561    24998
493    24969
161    24945
917    24925
921    24884
       ...
202      368
878      348
656      308
943      296
767      218
Length: 1000, dtype: int64

In [29]:

orders.sort_values()[::-1].index[0]

np.int64(561)

In [39]:
orders.sort_values()[::-1][0]

np.int64(869)

In [50]:
#Find the index of the highest order.
res=orders.sort_values()[::-1].index[0],orders.sort_values()[::-1][0]
res

(np.int64(561), np.int64(869))

In [41]:
orders.sort_values().index[0]

np.int64(767)

In [42]:
orders.sort_values().values[0]

np.int64(218)

In [34]:
#Find the index of the lowest order.
orders.sort_values().index[0],orders.sort_values().values[0]

(np.int64(767), np.int64(218))

In [35]:
# Calculate the total revenue after applying a 15% discount on every order.
discount15=orders*0.85
discount15.sum()

np.float64(10343788.55)

In [36]:
orders.sum()*0.85

np.float64(10343788.549999999)

In [37]:
#Find the number of orders above the average order value.
orders[orders>orders.mean()].size

497

In [38]:
#Find the difference between the highest and lowest order amount.
orders.max()- orders.min()

24780